### ISSUE TITLE
Cursor one position off in latest version?

### ISSUE THREAD

**Issue by lkamensky** [karlhorky/BlockCursorEverywhere#13] opened 2015-03-07 21:16 UTC
Very nice plugin! However, when I installed it today, there seemed to be a problem with the block cursor position in vi normal mode. Steps to reproduce:

1. Enter vi (or rather Vintage) normal mode.
2. Move the cursor (h, j, k or l). The block cursor does not follow the first cursor movement so the actual cursor and the block cursor differ by one position.

It worked fine earlier, so maybe something with the commits done today?

**Comment by myriasofo** [comment] 2015-03-08 05:14
I have the same problem on my machine and I agree that it just started today. The way the block follows the cursor - it's almost like a game of snake.

**Comment by myriasofo** [comment] 2015-03-08 05:24
After a little bit of testing, the problem seems to be with the time_difference tolerance. It's currently set to 0.016, but that be too long? I shortened it to 0.00016

**Comment by karlhorky** [comment] 2015-03-08 11:35
Hm, yes this is probably caused by #12. I cannot reproduce this error unfortunately on Sublime Text build 3065 on OS X 10.10.2. 

What build and OS do you have @myriasofo @lkamensky ?

**Comment by karlhorky** [comment] 2015-03-08 11:38
I think for the moment what I'll do is enable the fixes in #12 only when it's in Vintageous mode. With `0.00016` that causes a plugin crash when doing repetitive insert operations like <kbd>5</kbd>-<kbd>i</kbd>-<kbd>=</kbd>

**Comment by zjc0816** [comment] 2015-03-08 12:06
I have this problem too.
on Sublime Text build 3065, Ubuntu 14.04

**Comment by karlhorky** [comment] 2015-03-08 12:18
Okay, I've increased the frequency of the `on_selection_modified` function calls. Does this fix anything for anyone?

**Comment by karlhorky** [comment] 2015-03-08 12:22
I think probably generally it is a dangerous idea to set a hardcoded value in the plugin (since it probably has to do with some race condition), but until guillermooo/Vintageous#739 is fixed in Vintageous it provides a way to avoid the plugin crashes.

**Comment by zjc0816** [comment] 2015-03-08 12:41
It still doesn't work normally. I noticed that after I push <kbd>ctrl</kbd> + <kbd>`</kbd> to open the console and then close it, the block cursor follows the cursor movement correctly.

**Comment by lkamensky** [comment] 2015-03-08 12:44
I use build 3065 on Ubuntu Linux 14.10 and Windows 8.1 (possible to reproduce on both). Notice that I have not yet tried your new version, but I will. Thanks for the quick response.

**Comment by karlhorky** [comment] 2015-03-08 13:13
Just pushed `v1.0.2` with a small fix.

**Comment by karlhorky** [comment] 2015-03-08 13:13
@zjc0816 which version of the plugin do you have? Did you install manually in order to get the latest updates?

**Comment by karlhorky** [comment] 2015-03-08 13:42
`v1.0.2` is now in Package Control

**Comment by lkamensky** [comment] 2015-03-08 13:44
Still same problem with v1.0.2.

**Comment by zjc0816** [comment] 2015-03-08 13:52
An hour ago, I installed manually(copy it into my Packages/User folder). Just now, I remove the plugin and reinstall it. It isn't fixed.

**Comment by karlhorky** [comment] 2015-03-08 14:37
Strange, I tested it on a fresh Build 3065 on Windows 8.1 and Ubuntu 14.10 just now and I cannot see the error.

**Comment by karlhorky** [comment] 2015-03-08 14:40
@zjc0816 to manually install, you copy it into the `Packages` folder, not `Packages/User`

**Comment by karlhorky** [comment] 2015-03-08 14:41
Maybe try disabling other plugins or reinstalling Sublime Text?

**Comment by karlhorky** [comment] 2015-03-08 14:43
Hm, actually with Windows 8.1 now I believe I can reproduce the problem, after I reinstalled package control.

**Comment by karlhorky** [comment] 2015-03-08 14:57
It appears to be that `on_command_mode_change` is being fired three times for every movement. The second and third times are fired at the same time as the first one, causing them to be dropped.

I'll figure out a different way to throttle these events.

**Comment by zjc0816** [comment] 2015-03-08 15:06
I only copied 'SublimeBlockCursor.py'. I think it's ok because this file in plugin will be overrided by the one I copied.

**Comment by karlhorky** [comment] 2015-03-08 16:01
Okay, I've fixed the issue in Windows with `v1.0.3`. Please test and confirm or re-open.

**Closed** 2015-03-08 16:01 UTC
Labels: bug, needs feedback

**Comment by Goldiorl** [comment] 2015-03-08 20:20
I think it has been solved, at least on my computer
Windows 8.1/ST3 Build 3065
